### ISSUE TITLE
Music disc doesn't have tag

### ISSUE THREAD

**Issue by vizthex123** [izofar/bygone-nether#10]
It's lacking the `minecraft:music_discs` tag, which is a tad annoying.

**Comment by izofar** [comment]
I forgot about this tag, thank you for raising!

**Comment by vizthex123** [comment]
Anytime. Was going to report more issues (since I don't like filing a report for something small like this), but couldn't find any.

**Comment by izofar** [comment]
Fixed in v1.2.2

**Comment by vizthex123** [comment]
noice, thanks.
