### ISSUE TITLE
eventbus error whille loading up the mod

### ISSUE THREAD

**Issue by Pittol474** [izofar/bygone-nether#12]
[crash-reports_crash-2022-12-08_04.25.39-fml.txt](https://github.com/izofar/bygone-nether/files/10186801/crash-reports_crash-2022-12-08_04.25.39-fml.txt)

Hi, using ur mod in my modpack Triforge. Suddenly it started crashing on our server. Thats the crashlog that indicates its caused by Bygone Nether.

**Comment by izofar** [comment]
I need the entire `debug.log` to further address this. It seems like some other mod is trying to instantiate one of my classes with reflection, yet it shouldn't be doing that.

**Comment by izofar** [comment]
Closing per refactoring of entity registry and no additional information provided
