### ISSUE TITLE
Incompatibility with identity mod

### ISSUE THREAD

**Issue by Eragon117** [izofar/bygone-nether#13]
Bygone nether piglin brute cause MC to crash when identity mod menu is opened. 
[identity-vs-bygone.txt](https://github.com/izofar/bygone-nether/files/10226607/identity-vs-bygone.txt)
[crash1.txt](https://github.com/izofar/bygone-nether/files/10226609/crash1.txt)

**Comment by izofar** [comment]
Imho, the other author needs to make a change to their mod, since their implementation is way too intrusive to other mods. this issue and a recommended fix is posted [here](https://github.com/Draylar/identity/issues/488)
