### ISSUE TITLE
[Fabric] CurseForge files are marked as Forge

### ISSUE THREAD

**Issue by Poopooracoocoo** [izofar/bygone-nether#19]
### Describe the Bug

https://www.curseforge.com/minecraft/mc-mods/bygone-nether-fabric
![image](https://user-images.githubusercontent.com/51363864/221421694-04c7f971-015f-40ab-8fe5-e08b8612b94d.png)

### Reproduction Steps

N/A

### Expected Result

Files marked as being for Fabric

### Operating System

Windows 10

### Mod Version

1.2.1

### Minecraft Version

1.19.2

### Forge Version

N/A

**Comment by izofar** [comment]
Fixed
