### ISSUE TITLE
Game Crashing whenever i load a piglin manor 

### ISSUE THREAD

**Issue by Killercrab432** [izofar/bygone-nether#21]
### Describe the Bug

Been testing around with the Fabric 1.18.2 version of this mod, both the catacombs and citadel generate fine with no issues but as soon as i load in the chunks of the piglin manor my game crashes

also i am using the 1.2.2 version this was not selectable down below

### Reproduction Steps

1. Make new world
2. go to nether
3. /locate piglin manor
4. Either tp to it or fly in the direction either way my game will just instantly crash
5.
...

### Expected Result

For the game to not crash

### Crash Report or Log

https://pastebin.com/fU5Pws5k

### Operating System

Windows 10

### Mod Version

1.2.1

### Minecraft Version

1.18.2

### Forge Version

Fabric 0.14.17

### Other Mods

All mods are list in crash log

### Additional Context

![image](https://user-images.githubusercontent.com/105161116/224542387-714e1fd3-ef96-4f3b-b8b7-2b4de753085c.png)

this is the crash screen it states it could be fixed by allocation additional memory but this is false i have tested changing the allocated memory multiple times

**Comment by Killercrab432** [comment]
Can now confirm its a Compatibility issue with https://github.com/sf-inc/sihywtcamd

**Comment by izofar** [comment]
Closing, as it is an issue with [SIHYWTCAMD](https://github.com/sf-inc/sihywtcamd) handling mob passenger unsafely. this crashes on Piglin Manor generation because mounted mobs are spawned.
