### ISSUE TITLE
[1.19.2] Bygone Nether overriding vanilla bastion structure file unnecessarily 

### ISSUE THREAD

**Issue by TelepathicGrunt** [izofar/bygone-nether#23]
### Describe the Bug

Just fyi, don't override structure files just to add your biomes to it. This can break compat with other mods or datapacks unnecessarily. Instead, add your biomes to this minecraft biome tag that vanilla bastions uses to know what biomes they can spawn in: https://github.com/misode/mcmeta/blob/ce568022daf9a26bf6625e96fd56fb3e0f068c32/data/minecraft/tags/worldgen/biome/has_structure/bastion_remnant.json

### Reproduction Steps

Open project and see the file being overridden
![image](https://user-images.githubusercontent.com/40846040/229353182-3f0ec960-d43e-4cd0-812b-5586856e6db8.png)

### Expected Result

Biomes are added to the proper biome tags instead of needing to override the vanilla structure json

### Operating System

Windows 10

### Mod Version

1.2.1

### Minecraft Version

1.19.2

### Forge Version

43.2.6

### Additional Context

Also, side note, I made a compat datapack between Repurposed Structures and Bygone Nether to may my Jungle Fortress be in the style of your fortress!
https://www.curseforge.com/minecraft/texture-packs/repurposed-structures-bygone-nether-compat

**Comment by izofar** [comment]
Oh man, thank you for making that datapack! Looks awesome!

Bastion json fixed in [dcea627](https://github.com/izofar/bygone-nether/commit/dcea6274a67302d4e10117c9efff2ac5b6bd0e5d).
