### ISSUE TITLE
minecraft crashes when trying to render gilded netherite armor

### ISSUE THREAD

**Issue by username1419** [izofar/bygone-nether#24]
### Describe the Bug

my client crashes when attempting to render bygone nether's gilded(golden) netherite chestplate. the same for my friend who was playing on the same server

### Reproduction Steps

1. wear a golden gilded netherite chesplate
2. open up inventory or go into third person view

### Expected Result

client crashes immediately

### Crash Report or Log

https://pastebin.pl/view/1763e34a

### Operating System

WIndows 10

### Mod Version

1.2.1

### Minecraft Version

1.18.2

### Forge Version

fabric 1.18.2

### Other Mods

appleskin 2.4.1
balm 3.2.6
bettercombat 1.6.2
bookshelf 13.2.53
bygonenether 1.2.2
cardinal-components-api 4.2.0
cloth-config 6.3.81
clumps 8.0.0+17
data-attributes 1.3.2
elemental-creepers 1.4.2
enchancement 1.18-19
enchantment-descriptions 10.0.12
fabric-api 0.76.0
fabric-enchantments 0.7.2
fastdecay 1.1.0
ferrite-core 4.2.1
fps-monitor 1.2.1
friendly-fire 11.0.4
geckolib 3.0.80
hephaestus 3.5.2.155
hwgmod 1.1.12
impaled 1.1.3
incendium v5.0.7
inventoryessentials 4.0.3
inventorysorter 1.8.8
jei 10.2.1.1004
journeymap 5.9.5
medievalcraft 1.18.2-1.18.1
naturescompass 2.0.3
nullscape v1.1.3
origins 1.4.1
paradise-lost 1.6.9
pickyourpoison 1.0.8
player-animation-lib 1.0.2
playerex 3.4.2
phosphor 0.8.1
rottencreatures 1.0.0
sodium-extra 0.4.18
sodium 0.4.1
terra 6.0.0
tooltipfix 1.0.4
twilightforest 4.1.313
theoneprobe 5.1.3
travelers-backpack 7.1.23
trinkets 3.3.1
vanillatweaks 1.5.58
yungs-api 2.2.9
yungsbetternetherfortresses 1.0.0

**Comment by izofar** [comment]
Fixed in [8b74588](https://github.com/izofar/bygone-nether/commit/8b74588d97617340116381a72991520b3e2fc5a7)
