### ISSUE TITLE
[1.18.2] Crashes with Amplified Nether

### ISSUE THREAD

**Issue by DoctorMage** [izofar/bygone-nether#29]
### Describe the Bug

Example seed -2709617820162703822
/tp -10752 -51  -26112 Nether Coordsa

Going beyond vanilla nether build limit in basalt biomes will cause the game to crash

### Reproduction Steps

1.  Enter Nether
2. Find Basalt Biome go beyond vanilla build limit
3. 
...

### Expected Result

1.  Enter Nether
2. Find Basalt Biome go beyond vanilla build limit
3. Game does not crash

### Crash Report or Log

https://gist.github.com/DoctorMage/c63624d6f08d145d3dd202f2707416d0

### Operating System

Windows 10

### Mod Version

1.3.0

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Mod Loader Version

Forge 40.2.9

### Other Mods

Bygone Nether

### Additional Context

I have tested the same seed and coordinates in 1.19.2 and it seems fine

Unsure which mod to report this to so reported to both

**Comment by izofar** [comment]
Yes, this seems to be a problem with my mixin for keeping basalt features our of my structures. Fix pending

**Comment by izofar** [comment]
_Explanation:_ My mod originally contained a modded fortress that could spawn in basalt deltas, and I borrowed Repurposed structure's mixin to keep basalt columns from littering my structure. However, I extracted the modded fortress into its own mod, but forgot to remove the fortress from the NO_BASALT tag. Vanilla fortress are not jigsaw, but procedural, so this caused accessing chunks outside the 3x3 bounds.

**Comment by izofar** [comment]
I'll have this fixed in my latest version. But, because this is a datapack issue, you can remove `mincraft:fortress` from `data/bygonenether/tags/worldgen/configured_structure_feature/no_basalt.json` to fix this issue before my next release.

**Comment by izofar** [comment]
Fixed in [a6a61f3](https://github.com/izofar/bygone-nether/commit/a6a61f37c4a2787bd86b1336a636ef6b5d832859)
