### ISSUE TITLE
Server crash, but singleplayer works

### ISSUE THREAD

**Issue by CapNapu** [izofar/bygone-nether#30]
### Describe the Bug

Playing in single player works fine, but when I put the mod on a dedicated server, it always crashes.

### Reproduction Steps

1. Install Forge 36.2.34 Server
2. Place Bygone Nether 1.3.1.jar
3. Start the server

### Expected Result

No server crashes

### Crash Report or Log

https://gist.github.com/CapNapu/317489a0537c56200a6e10154895e165

### Operating System

W10

### Mod Version

1.3.0

### Minecraft Version

1.16.5

### Mod Loader

Forge

### Mod Loader Version

36.2.34

### Other Mods

Crashes with or without other mods, so it doesn't really matter

### Additional Context

The server runs under Java 8 - 361

**Comment by izofar** [comment]
Thanks for reporting,

Fixed in [4a53625](https://github.com/izofar/bygone-nether/commit/4a53625f798ed77cca3f9eeff6962cf53e0389c2), and a new jar has been uploaded to CurseForge, pending review.
