### ISSUE TITLE
Wrong warped nether bricks crushing recipe and balancing

### ISSUE THREAD

**Issue by biscuit-cookie** [izofar/bygone-nether#34]
### Describe the Bug

Hi! I noticed 2 problems related to warped nether bricks recipes in Create. 
Firstly, there are 2 crushing recipes, one of them should crush slabs, but it wrongly uses regular bricks.
Secondly, bricks block recipe requires 2 nether bricks and 2 warped roots, but gives 3 (or 5) bricks and sometimes 2 warped roots as crushing result. Therefore, these conditions create a way to farm nether bricks. I suggest using the slab crushing recipe for regular blocks and new one for slabs (as example, 1 slab -> 1 nether brick (75%) 1 warped root (50%))
Also, chiseled bricks have even worse crushing recipe, I suggest replacing it as well as regular ones
MC Version: 1.19.2
Mod version: 1.3.1

### Reproduction Steps

![image](https://github.com/izofar/bygone-nether/assets/142683244/aea94283-ef0d-4b84-b120-5d14dca4d95c)
///
![image](https://github.com/izofar/bygone-nether/assets/142683244/6acad3c0-46ee-4154-8ac8-755764e2a123)
![image](https://github.com/izofar/bygone-nether/assets/142683244/2c39b5ba-3903-4e34-ba13-a7bff19a4764)
![image](https://github.com/izofar/bygone-nether/assets/142683244/2afc569e-df50-454b-b242-16dd11bdeb95)

### Expected Result

![image](https://github.com/izofar/bygone-nether/assets/142683244/8054621a-e905-446b-b091-7b0769673391)
![image](https://github.com/izofar/bygone-nether/assets/142683244/d68cd60f-b1e9-4f15-bf7f-bd08987b8e37)
![image](https://github.com/izofar/bygone-nether/assets/142683244/9e10a0ee-9034-4a82-bbea-78b835c50782)

### Operating System

Windows 11

### Mod Version

1.3.0

### Minecraft Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.21

**Comment by izofar** [comment]
Great suggestion! Thanks for catching this

**Comment by izofar** [comment]
Fixed in [ea37ae3](https://github.com/izofar/bygone-nether/commit/ea37ae3107337af721c29e2c4a1961563a26c898) for 1.16.5, [0043317](https://github.com/izofar/bygone-nether/commit/004331724fa3f66bcd26e66709eddc82f3cb1ead) for 1.18.2, [25728fe](https://github.com/izofar/bygone-nether/commit/25728fe5002c9ec731984269ed3564455d51008f) for 1.19.2, and [cb38a20](https://github.com/izofar/bygone-nether/commit/cb38a20bf1ceb2a374f60bdf6994b433b594f54c) for 1.20.x
