### ISSUE TITLE
Fatal Error NoSuchMethodError with CTD on Minecraft 1.20.4

### ISSUE THREAD

**Issue by Aflaungos** [izofar/bygone-nether#38]
### Describe the Bug

NoSuchMethodError caused by CatacombStructure.method_38676
[crash-2024-01-01_19.21.13-client.txt](https://github.com/izofar/bygone-nether/files/13806346/crash-2024-01-01_19.21.13-client.txt)

### Reproduction Steps

1. Launch minecraft
2. Open world
3. Go to nether
4. Crash
5.
6.
...

### Expected Result

Working Nether dimension

### Operating System

Windows 11

### Mod Version

1.3.2

### Minecraft Version

1.20.1

### Mod Loader

Fabric

### Mod Loader Version

0.15.3

### Other Mods

Should be on the crash log

### Additional Context

Tested using alpha BCLib 3.30.1

**Comment by izofar** [comment]
The 1.20.1 version is not compatible with 1.20.4 due to Mojang's refactoring of the codebase. Marking closed because I have not yet updated Bygone Nether to 1.20.4
